### ISSUE TITLE
Onikakushi trash site "freeze" / stops continuing at trash site on day 4

### ISSUE THREAD

**Issue by Losig777** [07th-mod/guide#23] opened 2018-05-18 18:36 UTC
So my issue is:
At the trash site on Day 4 of Onikakushi when Keiichi pulls out the doll the game always freezes or basically nothing happens afterwards anymore. I tried reinstalling and also checked if I did something wrong when patching, but that doesn't seem to be it.
![higurashi bug](https://user-images.githubusercontent.com/39412505/40243210-f7753af4-5abf-11e8-8048-4927626b186b.jpg)
This is the last scene that plays. Afterwards I see the sprite of Rena disappearing as it's probably supposed to story wise and then I'm just getting this scene and nothing happens anymore.
![nothing anymore](https://user-images.githubusercontent.com/39412505/40243496-a5a1045a-5ac0-11e8-8fca-d04e6472c9f7.jpg)
This is how far I can get in the story and then nothing anymore.

The most interesting thing is that the game isn't exactly freezing. For example if I want to quit it it still shows that it's responding as you can see here and asking me if I really want to quit. 
![still responding](https://user-images.githubusercontent.com/39412505/40243830-8693afda-5ac1-11e8-9e00-0d603eae97a5.jpg)
However I can't press right click to go to the menu anymore once I'm at that scene and the menu on the right isn't showing anymore either.

For testing purposes I have also now used an unpatched version to skip through day 4 and 5 and then used the patched version to do a chapter jump to day 5. 
Day 5 till the end of the game works completely without any issues with the patched game. 
*Conclusion*:  the issue must have something to do with Day 4 and specifically the trash site scene there after Keeichi got the doll out and Rena vanishes off screen (see the first image)

[ *FIXED* Also another issue as you can see in the images on the left side I somehow can't get the F10 Flag Monitor turned off anymore. I only turned it on once in onikakushi when trying to somehow look for the issue of the "freeze" and after not being able to turn the flag window off again I didn't dare to try it in the other chapters. 
No matter which keys I press or not I can't seem to turn it off anymore. So I'm not sure if I'm just stupid or if the flag window is somehow bugged.
It also doesn't matter if I do a fresh install of the game and the mod - the config even after a reinstall seems to stay the same and automatically turns the F10 Flag monitor on. I'm not sure how to reset that config. Is there any way to get this turned off again? 
*Edit*: For some reason after the chapter jump of Day 5 I was able to turn the flag window on and off again simply with F10 again. I don't know why, but it works again. At the time I made the pictures though it didn't respond at all.
The trash site problem on day 4 remains however ]

[ Sidenote: In the screenshots I don't have the UI mod installed (and also tried to remove the voices to check if there is an issue with the voices) but whether or not it's installed or not and whether not the voices are turned on or are removed it doesn't change this issue at all and isn't affecting anything.

I also have no issues with Chapter 2-5 they all work flawlessly from beginning to end including all the tips. So for the rest and also the rest of chapter 1 from Day 5 onwards  I can only say that they're awesome and working perfectly. A job well done and I love it! ]

**Comment by ItaloKnox** [comment] 2018-05-18 18:40
Hi, you're on the wrong side to report issues. If you find anything else, report them [here](https://github.com/07th-mod/onikakushi/issues).

About your issue, [try downloading this file](https://github.com/07th-mod/onikakushi/archive/master.zip) and extracting the ``Update`` folder only inside the ``StreamingAssets`` folder that is inside your game folder. Overwrite the files, then go inside the ``CompiledUpdateScripts`` folder and delete all files there. After that boot the game and see if the issue was fixed. Please report here if it works because we need to push a hotfix for that!

**Comment by enumag** [comment] 2018-05-18 19:00
Closing as duplicate of https://github.com/07th-mod/onikakushi/issues/171.

Fix released in [v5.6.1](https://github.com/07th-mod/onikakushi/releases/tag/v5.6.1).

Thanks for reporting.

**Closed by enumag** 2018-05-18 19:00 UTC
